import { TypeEnum } from "../../enum/pokemonEnum";

export const cardBgClass = {
    [TypeEnum.BUG]: "bg-green-200",
    [TypeEnum.DARK]: "bg-gray-400",
    [TypeEnum.DRAGON]: "bg-blue-400",
    [TypeEnum.ELECTRIC]: "bg-yellow-200",
    [TypeEnum.FAIRY]: "bg-pink-200",
    [TypeEnum.FIGHTING]: "bg-red-200",
    [TypeEnum.FIRE]: "bg-orange-400",
    [TypeEnum.FLYING]: "bg-sky-200",
    [TypeEnum.GHOST]: "bg-indigo-900",
    [TypeEnum.GRASS]: "bg-green-500",
    [TypeEnum.GROUND]: "bg-amber-600",
    [TypeEnum.ICE]: "bg-teal-100",
    [TypeEnum.NORMAL]: "bg-gray-200",
    [TypeEnum.POISON]: "bg-purple-400",
    [TypeEnum.PSYCHIC]: "bg-rose-400",
    [TypeEnum.ROCK]: "bg-stone-300",
    [TypeEnum.STEEL]: "bg-slate-500",
    [TypeEnum.WATER]: "bg-blue-300",
}

export const spriteBgClass = {
    [TypeEnum.BUG]: "bg-green-300",
    [TypeEnum.DARK]: "bg-gray-500",
    [TypeEnum.DRAGON]: "bg-blue-600",
    [TypeEnum.ELECTRIC]: "bg-yellow-300",
    [TypeEnum.FAIRY]: "bg-pink-300",
    [TypeEnum.FIGHTING]: "bg-red-300",
    [TypeEnum.FIRE]: "bg-orange-500",
    [TypeEnum.FLYING]: "bg-sky-300",
    [TypeEnum.GHOST]: "bg-indigo-800",
    [TypeEnum.GRASS]: "bg-green-600",
    [TypeEnum.GROUND]: "bg-amber-700",
    [TypeEnum.ICE]: "bg-teal-200",
    [TypeEnum.NORMAL]: "bg-gray-300",
    [TypeEnum.POISON]: "bg-purple-500",
    [TypeEnum.PSYCHIC]: "bg-rose-500",
    [TypeEnum.ROCK]: "bg-stone-400",
    [TypeEnum.STEEL]: "bg-slate-600",
    [TypeEnum.WATER]: "bg-blue-400",
}