import { TypeEnum } from "../../enum/pokemonEnum";

export const cardBgClass = {
    [TypeEnum.BUG]: "bg-green-300",
    [TypeEnum.DARK]: "bg-slate-500",
    [TypeEnum.DRAGON]: "bg-blue-300",
    [TypeEnum.ELECTRIC]: "bg-yellow-200",
    [TypeEnum.FAIRY]: "bg-pink-200",
    [TypeEnum.FIGHTING]: "bg-red-200",
    [TypeEnum.FIRE]: "bg-orange-400",
    [TypeEnum.FLYING]: "bg-sky-200",
    [TypeEnum.GHOST]: "bg-indigo-700",
    [TypeEnum.GRASS]: "bg-green-500",
    [TypeEnum.GROUND]: "bg-amber-600",
    [TypeEnum.ICE]: "bg-teal-100",
    [TypeEnum.NORMAL]: "bg-gray-200",
    [TypeEnum.POISON]: "bg-purple-400",
    [TypeEnum.PSYCHIC]: "bg-rose-300",
    [TypeEnum.ROCK]: "bg-stone-300",
    [TypeEnum.STEEL]: "bg-slate-400",
    [TypeEnum.WATER]: "bg-blue-300",
}

export const spriteBgClass = {
    [TypeEnum.BUG]: "bg-green-500",
    [TypeEnum.DARK]: "bg-slate-700",
    [TypeEnum.DRAGON]: "bg-blue-500",
    [TypeEnum.ELECTRIC]: "bg-yellow-400",
    [TypeEnum.FAIRY]: "bg-pink-400",
    [TypeEnum.FIGHTING]: "bg-red-400",
    [TypeEnum.FIRE]: "bg-orange-600",
    [TypeEnum.FLYING]: "bg-sky-400",
    [TypeEnum.GHOST]: "bg-indigo-900",
    [TypeEnum.GRASS]: "bg-green-700",
    [TypeEnum.GROUND]: "bg-amber-800",
    [TypeEnum.ICE]: "bg-teal-300",
    [TypeEnum.NORMAL]: "bg-gray-300",
    [TypeEnum.POISON]: "bg-purple-600",
    [TypeEnum.PSYCHIC]: "bg-rose-500",
    [TypeEnum.ROCK]: "bg-stone-500",
    [TypeEnum.STEEL]: "bg-slate-600",
    [TypeEnum.WATER]: "bg-blue-500",
}